spring:
  application:
    name: mlzj-client
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 20003
feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
  hystrix:
    enabled: true
  httpclient:
    enabled: true #feign启用httpclient
  compression:
    request:
      enabled: true # 请求响应的压缩开启
    response:
      enabled: true
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #hystrix 超时时间
ribbon:
  connectTimeOut: 5000 #一般情况下ribbon超时时间应该短与hystrix
  readTimeOut: 2000
  MaxAutoRetries: 1 #最大重试数
  MaxAutoRetriesNextServer: 1 # 最大重试的机器数，不包括请求到的机器
  eager-load:
    enabled: true
    clients: mlzj-order #开启ribbon饥饿加载,默认ribbon在调用时才会加载，改为启动加载，解决第一次调用可能会发生的超时

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,refresh #开放断路器被仪表盘监控
#apollo:
#  bootstrap:
#    enable: true
#    namespaces: application
#  meta: http://localhost:8080 #apollo metaServer地址
