server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mlzjsecurity?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  thymeleaf:
    prefix: classpath:/templates/page/
    cache: false