server:
  port: 8889
  tomcat:
    max-threads: 300
    accept-count: 100
    max-connections: 8192
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false