server:
  port: 20007
spring:
  application:
    name: mlzj-auth-server
  redis:
    host: localhost
    port: 6379
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/mlzjcloudauth?characterEncoding=utf8&readOnlyPropagatesToServer=false&rewriteBatchedStatements=true&useInformationSchema=false&useSSL=true
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  level:
    root: debug