spring:
  application:
    name: mlzj-order
server:
  port: 20002
eureka:
  client:
    service-url:
      defaultZone: http://mlzj:mlzj1234@localhost:8761/eureka
    initial-instance-info-replication-interval-seconds: 10 #实例信息变更同步到eureka间隔时间
  instance:
    prefer-ip-address: true  #开启ip显示
    lease-renewal-interval-in-seconds: 10 #每隔多少秒发送一次心跳信息
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream #开放断路器被仪表盘监控
feign:
  hystrix:
    enabled: true